### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by rmormando** [KolmogorovLab/hapdup#22]
Hi I posted this issue to the margin git repository but I figured I would ask it here as well:

I'm trying to install HapDup and I'm at the step where I need to install margin with this command:

`#build and install Margin 
pushd submodules/margin/ && mkdir build && cd build && cmake .. && make && cp ./margin $CONDA_PREFIX/bin/ && popd`

I have created the 'build' directory and was able to successfully run cmake .. but when I go to run make I get this error:
```
/Users/hapdup/submodules/margin/impl/bubbleGraph.c:7:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/marginLib.dir/impl/bubbleGraph.c.o] Error 1
make[1]: *** [CMakeFiles/marginLib.dir/all] Error 2
make: *** [all] Error 2
```
I've tried reinstalling the xz package with no luck and I'm completely lost at this point. Can someone help me understand this error and a way to fix it?

**Comment by fenderglass** [comment]
Looks like you need the development headers for lzma library, not just the library itself. They should be available via your OS' package manager.

Best,
Mikhail
