### ISSUE TITLE
Flye polisher fails on a bam with `--eqx`

### ISSUE THREAD

**Issue by fenderglass** [KolmogorovLab/hapdup#24]
Need to update CIGAR parser in `sam_parser.py` in Flye.

**Comment by caspargross** [comment]
You fixed support for '=' in CIGAR strings in flye already. 
https://github.com/fenderglass/Flye/commit/fdcec7f82c8e1826db1b9a348485f63a899468cf
Can you build a new container image including the fix?

Thanks, Caspar

**Comment by fenderglass** [comment]
Oups, sorry for my late response! It should be fixed in the `hapdup:0.12` now.
