### ISSUE TITLE
Support for CLR reads?

### ISSUE THREAD

**Issue by ptrebert** [KolmogorovLab/hapdup#32]
Hi,
I was a bit surprised to see that there is no support for PacBio CLR reads (out-of-the-box at least). I have a bunch of flye CLR assemblies; do you think it's worth a shot to run hapdup on those (if so, using which setting)?
Best,
Peter

**Comment by ptrebert** [comment]
Just to be more precise, the readme claims compatibility with CLR ...

```
[...] HapDup works with either Oxford Nanopore or PacBio (HiFi or CLR).
```
... but the presets only apply to ONT and Hifi (as well as the hard-coded default PEPPER/MARGIN model files). This is what confuses me.

**Comment by fenderglass** [comment]
The manual citing Pacbio CLR is indeed my mistake - it should be removed..

**Comment by ptrebert** [comment]
I fully agree on the fact that the field has largely abandoned CLR reads, I just happen to have a request on my desk about analyzing some old-ish datasets. Yes, I did try to run hapdup with the existing model, but it (predictably) failed.

So, overall, I'll close this ticket now; except for the minor correction to the readme, there is not much more discuss I guess. Thanks.
