### ISSUE TITLE
Cannot Find HapDup in Conda

### ISSUE THREAD

**Issue by FrostFlow13** [KolmogorovLab/hapdup#33]
Hello! 

I am trying to install HapDup using conda, specifically by following the instructions listed in the README.md:

`#create a new conda environemnt and activate it`
`conda create -n hapdup python=3.8`

However, conda is saying that hapdup is not available from conda-forge, bioconda, or the default packages. The exact error text is as follows:

> conda create -n hapdup_env hapdup python=3.8
> Collecting package metadata (current_repodata.json): done
> Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - hapdup
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/linux-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://conda.anaconda.org/bioconda/linux-64
>   - https://conda.anaconda.org/bioconda/noarch
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

Trying to search https://anaconda.org/, I also cannot seem to find it! Are these instructions old/placeholders, or am I perhaps doing something wrong? 

Thank you,
Andrew

**Comment by FrostFlow13** [comment]
Nevermind, I just realized my mistake - that's not a package for HapDup, that's just naming the environment. My apologies!

**Comment by nicolo-tellini** [comment]
Hello, 

is hapdup available in conda?

thanks

**Comment by mikolmogorov** [comment]
@nicolo-tellini not on conda, unfortunately - it is difficult because of DeepVariant dependency.

**Comment by nicolo-tellini** [comment]
I see, thanks a lot for replying @mikolmogorov 

have a good day
