### ISSUE TITLE
Issue with Hapdup

### ISSUE THREAD

**Issue by santoshe1** [KolmogorovLab/hapdup#39]
Hello Team,

Thank you for this wonderful tool. I am processing a GIAB dataset - HG002 and would like to report a bug/error during the run of HapDup with Flye throwing an error to not create polished_1.fasta. Please see the error log below:

[](Nov 14, 2023 09:17:51:hapdup.fasta_parser.FastaError: [Errno 2] No such file or directory: '/obs/research_ont/test/hapdup/HG002/1/task-2-hapdup/hapdup/HG002/flye_hap_1/polished_1.fasta'
Nov 14, 2023 09:17:51:    raise FastaError(e)
Nov 14, 2023 09:17:51:  File "/usr/local/lib/python3.8/dist-packages/hapdup/fasta_parser.py", line 74, in stream_sequence
Nov 14, 2023 09:17:51:    for hdr, seq in stream_sequence(filename):
Nov 14, 2023 09:17:51:  File "/usr/local/lib/python3.8/dist-packages/hapdup/fasta_parser.py", line 37, in read_sequence_dict
Nov 14, 2023 09:17:51:    fasta_dict = fp.read_sequence_dict(input_fasta)
Nov 14, 2023 09:17:51:  File "/usr/local/lib/python3.8/dist-packages/hapdup/apply_inversions.py", line 23, in apply_inversions
Nov 14, 2023 09:17:51:    apply_inversions(inversions_hp, polished_flye_hap[hp], final_dual_asm[hp], hp)
Nov 14, 2023 09:17:51:  File "/usr/local/lib/python3.8/dist-packages/hapdup/main.py", line 266, in main
Nov 14, 2023 09:17:51:    sys.exit(main())
Nov 14, 2023 09:17:51:  File "/usr/local/bin/hapdup", line 8, in <module>
Nov 14, 2023 09:17:51:Traceback (most recent call last):
Nov 14, 2023 09:17:51:
Nov 14, 2023 09:17:51:During handling of the above exception, another exception occurred:)

Could you please help me resolve this issue?

Thank you

**Comment by fenderglass** [comment]
Could you please submit `hapdup.log` and log files from `flye_*` directories inside the hapdup output dir?
