### ISSUE TITLE
Are Dorado reads supported?

### ISSUE THREAD

**Issue by Axze-rgb** [KolmogorovLab/hapdup#40]
Hello, the doc suggests only Guppy5+ are supported, but it's unclear to me if it means "higher version of Guppy" or "anything coming after". Since Dorado has an error profile that is quite different from Guppy's, I wonder if you recommend HapDup with dorado reads.

Thanks a lot 

Alex

**Comment by fenderglass** [comment]
Hi Alex,

Yes, we've done quite a bit of assemblies with Dorado - it should work fine!

Misha

**Comment by Axze-rgb** [comment]
Awesome, thanks :)
