### ISSUE TITLE
Phase block and hapdup_phased_{1,2}.fasta

### ISSUE THREAD

**Issue by WeichenZhou** [KolmogorovLab/hapdup#43]
Hi @mikolmogorov,

Thanks a lot for creating such a great tool!
I am new to the genome assembly field. Could you provide some information regarding the relationship between phase block (phased_blocks_hp{1,2}.bed) and hapdup_phased_{1,2}.fasta? Will the reads from hapdup_phased_{1,2}.fasta fall into the phase block bed? Or if I have to use the hapdup_phased_{1,2}.fasta data, should I parse the phase block/set information by myself?

Looking forward to your reply.

Best,
Arthur

**Comment by mikolmogorov** [comment]
Hi Arthur,

In `phased_blocks{1,2}.fasta` contigs are already split at the phase blocks boundaries. You only need `phased_blocks_hp{1,2}.bed` if you are working with the dual assembly.

**Comment by WeichenZhou** [comment]
Hi Mikhail,

Thanks a lot for the reply. What if I observed two contigs that overlapped with each other in aligned phased_blocks{1,2}.fasta? I am not sure how to interpret this.

Best,
Arthur

**Comment by mikolmogorov** [comment]
Hi Arthur - contig alignments may overlap because of mapping uncertainties / errors. Most likely you may have a contig containing a repetitive sequence - its mapping may overlap with other (correctly mapped) contigs.

**Comment by WeichenZhou** [comment]
Hi Mikhail, sorry for the idle. Thank you for your information!!
